shiftstack/dev-install

- .gitignore
- Makefile
Make editors happy and add the proper extension to the Ansible
inventory.
> Makefile: Add 'yaml' extension to inventory

- Makefile
> Allow user to be set on make config

- playbooks/install_stack.yaml
- playbooks/templates/standalone_parameters.yaml.j2
> Workaround for broken Amphora image in OSP17

- playbooks/prepare_stack.yaml
Or instances don't get an IP and can't resolve domain names from
Internet.
> provider network: set dns and enable DHCP

- playbooks/files/containers-prepare-parameters.yaml
- playbooks/install_stack.yaml
- playbooks/roles/network_info/tasks/main.yaml
- playbooks/templates/containers-prepare-parameters.yaml.j2
- playbooks/templates/standalone_parameters.yaml.j2
- playbooks/vars/defaults.yaml
- Change location of dev-install-network-info.yaml
- Templatize ContainerImagePrepare
- Allow to override net-config in 16
> Improvements to support other OSP versions

- playbooks/templates/tripleo-deploy.sh.j2
> Add StdErr in tripleo deploy logs

- example-overrides/local-overrides-osp16-2.yaml
> Provide example of overrides to deploy OSP16.2

- playbooks/templates/standalone_parameters.yaml.j2
- playbooks/vars/defaults.yaml
> Add params for neutron bridge mapping and flat networks

- Makefile
- README.md
- example-overrides/local-overrides-centos8-tripleo-train.yaml
- playbooks/install_stack.yaml
- playbooks/local_requirements.yaml
- playbooks/prepare_host.yaml
- playbooks/roles/operators/tasks/main.yaml
- playbooks/vars/defaults.yaml
- Install local requirements to use TripleO Ansible Operators
- CentOS / RDO support
> Move to t-o-a & support centos/rdo

- README.md
- playbooks/vars/defaults.yaml
- OSP 17 is very unstable
- OSP 16.2 is what most of us are testing right now
> Change defaults for OSP version

- playbooks/install_stack.yaml
- Remove ceph-ansible duplicate
- Fix the issue when Ceph is disabled, which was producing wrong data in
Ansible.
> Fix ceph_env fact and remove duplicate

- playbooks/install_stack.yaml
> Fix Ansible syntax

- playbooks/install_stack.yaml
Or the task that create the sriov services fact will fail.
> Add default sriov_interface in sriov_services_fact

- playbooks/templates/standalone_parameters.yaml.j2
We need to check if the variable is defined, not if it's true/false.
> Fix ceph_devices condition

- playbooks/prepare_stack.yaml
Sorry I missed it in my previous PR.
> Fix password for openshift user in clouds.yaml

- playbooks/prepare_host.yaml
- you need too recent version of ansible to call the new namespace
- the condition was wrong
> Fix ssh authorized keys

- playbooks/local_os_client.yaml
This allows referencing the CA cert without putting it in the local host
trust bundle.
/cc @mandre
> Create and use user-local copy of ca cert

- .github/workflows/ansible-lint.yml
- playbooks/network.yaml
Another fix to the existing NIC disable code, and an additional fix for some weird phantom nics we're seeing in PSI.
> Disable nics

- playbooks/network.yaml
new task to save nmstate_routes
updated the network_state variable to include static route information
> added the ability to save static routes preserving the default route

- playbooks/prepare_stack.yaml
Let's create a small flavor in between the tiny and medium.
> Add m1.small flavor

- example-overrides/local-overrides-osp16-2.yaml
Adds  information to example file
> Example of rhsm deployment

- playbooks/install_stack.yaml
Otherwise it'll fail with permissions error.
> RHSM: unregister with sudo

- .github/workflows/ansible-lint.yml
> CI: workaround for ansible-lint 'rich' problem

- playbooks/templates/standalone_parameters.yaml.j2
Co-Authored-By: Emilien Macchi <emilien@redhat.com>
> Make sure neutron_mtu setting is enforced in any type of installations

- playbooks/templates/standalone_parameters.yaml.j2
- playbooks/vars/defaults.yaml
This will allow to override the heat resource registry to enable any
service that we want.
> Add extra_heat_resource_registry parameter

- playbooks/prepare_host.yaml
Some internal changes on URLs.
> Update RH URls

- README.md
EPEL is not compatible, we should document that to avoid user errors.
> README: document that EPEL is not compatible

- playbooks/roles/operators/tasks/main.yaml
Let the user deal with their version of Ansible.
> operators: don't force version anymore

- playbooks/prepare_host.yaml
> prepare: remove RH 2015 cert
