playbooks/templates/standalone_public_route.service.j2
playbooks/templates/standalone_public_snat.service.j2

When executing the units, systemd errors with:
```
[/etc/systemd/system/standalone_public_route.service:7] Executable path is not absolute, ignoring: ip route replace [...]
```
With this change, `ip` and `iptables` are called using their expected
absolute path.

systemd: Use absolute paths in Exec

---

playbooks/prepare_stack.yaml

It's not needed to get a functional deployment of OCP and currently
breaks the playbook anyway.

Comment out the `Configure resources for openshift user` task

---

Makefile
README.md
playbooks/local_os_client.yaml
playbooks/templates/env.sh.j2
playbooks/vars/defaults.yaml

The variable was previously never set. This now sets it to `standalone`
unless it is set somewhere else.

Set default cloudname

---

playbooks/prepare_stack.yaml

In shiftstack-ci, we use m1.large name for flavors of workers, so let's
use 25GB of disk as it's a minimum.

flavor: increase storage for m1.large

---

playbooks/templates/standalone_parameters.yaml.j2
playbooks/templates/tripleo-deploy.sh.j2

Enable Octavia (Load Balancer as a Service in OpenStack) by default,
since it's used when enabling Kuryr instead of OpenShiftSDN.
Note that we have to specify both OctaviaGenerateCerts and
OctaviaCaKeyPassphrase, to make the deployment happy but since we don't
use the Amphora driver (we use OVN-provider), it doesn't matter that the
passphrase is not secured.

Enable Octavia

---

playbooks/install_stack.yaml
playbooks/templates/standalone_parameters.yaml.j2

This is needed so Octavia works fine when Kuryr tries to bootstrap
loadbalancers used for l7 (not using OVN yet).
Also remove the comments that says that we don't use Amphora, this was
wrong.

octavia: download amphora images

---

playbooks/prepare_stack.yaml

So nova can schedule VMs on that network.

Set the provider network as shared

---

playbooks/prepare_stack.yaml
playbooks/vars/defaults.yaml

In some cases (Edge, CI, etc), we don't want to manage the RHCOS image
from dev-install. We have our own tooling to download it and push it to
the Glance stores.

Allow to not manage RHCOS image

---

playbooks/install_stack.yaml

If Ceph is being deployed, we need ceph-ansible.

Install ceph-ansible

---

playbooks/install_stack.yaml
playbooks/templates/standalone_parameters.yaml.j2
playbooks/templates/tripleo-deploy.sh.j2
playbooks/vars/defaults.yaml

* install ceph-ansible, which is required if you deploy Ceph in your
cloud.
* Switch CloudName to be the FQDN of the cloud, not an IP address.
* Add a parameter to change the default role for Standalone
* Use --keep-running, so an operator can query the Heat ephemeral stack
for standalone. Useful in the case of Edge since we need to extract
Heat data like endpoint-map, etc.

Few improvements (useful for Edge)

---

.gitignore
Makefile
playbooks/certs.yaml
playbooks/roles/simpleca/defaults/main.yml
playbooks/roles/simpleca/tasks/main.yaml

Generates root CA which passes validation by openshift-install when
passed in additionalTrustBundle.
Generates signed cert for quay service running on host.

certs: Add a `make certs` target

---

.gitignore
playbooks/roles/simpleca/tasks/main.yaml

The right file extension for an openssl certificate is .crt.

certs: use crt vs cert

---

README.md

OSP 17 requires RHEL 8.3 or greater, this change calls that out
specifically.

update readme with more recent version information

---

playbooks/network.yaml

It's not installed by default on RHEL8 and needed for the nat rule to
be created.

network: add iptables in dependencies

---

playbooks/templates/dev-install_net_config.yaml.j2
playbooks/vars/defaults.yaml

Allow the user to override the network config when they know what
they're doing, if not we use the opinionated template like before.

Enable advanced nic configs (e.g. SR-IOV)

---

playbooks/vars/defaults.yaml

My bad, I missed it in the last PR.
Also changing the tag to match with what is on tested already.

defaults: add missing namespace for OSP containers

---

playbooks/install_stack.yaml
playbooks/prepare_host.yaml
playbooks/prepare_stack.yaml
playbooks/roles/network_info/tasks/main.yaml
playbooks/templates/standalone_parameters.yaml.j2
playbooks/vars/defaults.yaml

For the developer use case, we use a loop device to install LVM volumes
for ceph.
This patch will add two options to dev-install:
* ceph_enabled (false by default)
* ceph_loop_device_size (10 GB by default)
It will take care of creating a loop device that is reboot-persistent,
and then use it for the deployment of Ceph via ceph-ansible.
It'll also dynamically load the environment and services if we want
Ceph enabled.
This addition does not configure Ceph for production, so in the
OpenShift on OpenStack use-case, keep in mind that the Ceph
performances won't be great on loop devices. In other words, booting
the cluster nodes from volumes will be problematic because of perf
requirements for etcd.
It also adds nodisk flavors for both large and xlarge. They can be
useful when deploying OCP …

Add support to install Ceph via loop device

---

playbooks/templates/standalone_parameters.yaml.j2
playbooks/vars/defaults.yaml

extra_heat_params is a new parameter that'll let you set or override any
Heat parameter.
e.g.
```
extra_heat_params:
NovaReservedHostMemory: 4096
NovaPCIPassthrough:
- address: "0000:04:00.1"
```
Note that if a Heat param is defined in extra_heat_params and also in standalone_parameters,
the former will override the latter which can be useful if you need specific configs.

Add new parameter "extra_heat_params"

---

playbooks/prepare_host.yaml

We can't customize the loop device name (it errors), so let's just use
loop1 like it's done by standard loops.

ceph: fix loop device name

---

README.md
playbooks/install_stack.yaml
playbooks/templates/dev-install_net_config.yaml.j2
playbooks/templates/standalone_parameters.yaml.j2
playbooks/vars/defaults.yaml

* Add an interface to easily add new services into the default Standalone role.
* Make it so SR-IOV and DPDK configs are independently configurable
* Configure SR-IOV + DPDK parameters in standalone_parameters.
* Configure the SR-IOV NIC.
* Modify the Standalone role with SR-IOV services
* Reboot the node at the end of the deployment to apply Kernel changes.

Enable SR-IOV + DPDK support

---

playbooks/templates/standalone_parameters.yaml.j2

Since we use a loop device for the Ceph disk, performances wouldn't be
great enough to boot VMs (e.g. OCP cluster) and would lead to problems
later.
If anyone wants wants to overrides this option, they can do it via:
```
extra_heat_params:
NovaEnableRbdBackend: true
```
To use at your own risks...

If ceph is enable, disable Nova RBD

---

playbooks/install_stack.yaml
playbooks/vars/defaults.yaml

Loading standalone_parameters.yaml early meant that values would be
overridden by defaults specified in subsequent environments.
Specifically this prevented NovaEnableRbdBackend: false working because
ceph enables it by default, and ceph was loaded later.

Ensure standalone_parameters.yaml is last in tripleo deploy

---

playbooks/templates/dev-install_net_config.yaml.j2

If the interface that is used for br-ex (e.g. eth0) had a specific MTU,
we need to configure the bridge with the right MTU value otherwise we
force it to 1500 and it can causes issues.

Configure the right MTU for br-ex

---

playbooks/prepare_stack.yaml

It's needed otherwise it defaults to Cinder V2 API.

clouds.yaml: configure volume_api_version

---

playbooks/prepare_stack.yaml

It seems like that admin credentials created by TripleO
don't have a volume_api_version so we need to set a default for the
openshift user (otherwise it fails to destroy OCP cluster).
'3' is a safe default that works for both OSP16 and tripleo master.

Set default for volume_api_version

---

playbooks/prepare_stack.yaml

If Manila is enabled, let's create the share type so the user can start
using manila without creating it manually.

Automate manila share type creation

---

playbooks/prepare_host.yaml

For our users on CentOS, we need to ensure that they're on Stream or
they'll have packaging issue during TripleO deployment.
Same for container-tools, it's expected that we use 3.0 from now to get
newest Podman.

Migrate a host to CentOS stream && manage container-tools

---

.gitignore
Makefile
README.md

Most of us maintain multiple overrides depending where they deploy.
Let's allow our users to maintain multiple files, e.g.:
- local-overrides-beaker.yaml
- local-overrides-vexxhost.yaml
- etc
And when deploying they do: `make osp_full
overrides=local-overrides-beaker.yaml`.
This is backward compatible and the default will remain
local-overrides.yaml.

Allow to maintain multiple override files

---

playbooks/prepare_stack.yaml

https://bugzilla.redhat.com/show_bug.cgi?id=1960710
```
[stack@foch ~]$ rpm -qa|grep manilaclient
python3-manilaclient-2.6.0-0.20210323054047.1075210.el8.noarch
[stack@foch ~]$ openstack share type create cephfsnfstype false
Version 2.63 is not supported by the API. Minimum is 2.0 and maximum is 2.60. (HTTP 406) (Request-ID: req-cb62d943-ea63-4cd2-b3d9-5130bb3b0e1a)```
It doesn't work, it seems that the version of manilaclient is too recent for Manila, when running from the standalone host on master. Let's just revert that for now and re-implement later when packaging is correct.

Bug 1960710: Revert "Automate manila share type creation"

---

playbooks/install_stack.yaml
playbooks/vars/defaults.yaml

We already have safe defaults on RHEL/OSP for cip_config, where if it's
not defined we download the CIP from internal puddles and it's fine.
However when deploying on CentOS, we don't have safe defaults, so let's
add safe defaults which are:
* using CIP from tripleo-common master
* tripleo_repos_stream set to True

Download CIP from upstream/master if cip_config not defined on CentOS

---

playbooks/prepare_stack.yaml
playbooks/vars/defaults.yaml

For security purposes, it can be useful to override the default
password "password" that was set before with something more secure.

Allow to override openshift password in Keystone

---

Makefile

Not every system runs bash by default (e.g. systems provided by Github
CI), so if we want the commands to run fine (e.g. `echo -e`) we need to
force the SHELL to be bash.

Makefile: force the shell to be bash

---

example-overrides/local-overrides-centos8-tripleo-train.yaml
example-overrides/local-overrides-osp16-2.yaml
playbooks/install_stack.yaml

In OSP16, HAproxy isn't deployed with Pacemaker by default which
apparently can cause issues if the public IP is the same as the control
plane IP.
To counter that, we simply need to turn the services that can be HA to
be deployed by Pacemaker.
Also, it removes the need of having the control plan IP to be the same
as the public IP.

Enable TripleO HA services by default

---

playbooks/prepare_host.yaml
playbooks/vars/defaults.yaml

It can be handy when deploying & sharing environment among the team, to
pre-configure who will have access and dev-install will add the keys.

Allow to configure authorized SSH keys for stack user

---

playbooks/prepare_stack.yaml

- Revert "Revert "Automate manila share type creation""
- manila: force OS_SHARE_API_VERSION to 2.60 - context is explained in BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1960710

Manila: re-enable share create

---

playbooks/install_stack.yaml

We need to bind Ganesha to the control plane or the NFS mounts are not
binding on the control plane, and then the client will try to use the
public IP to mount, and it's wrong.
Tested against a real environment.

Fix Ganesha binding when Manila is enabled

---

playbooks/vars/defaults.yaml

Instead of current-tripleo-dev which is actual master, let's use
current-tripleo which is a repo that is tested, from master, so might
be lagging a bit but at least better tested.

Use current-tripleo by default

---

example-overrides/local-overrides-centos8-tripleo-train.yaml
playbooks/templates/standalone_parameters.yaml.j2

2 changes:
To help anyone who wants to deploy TripleO train, will be able to use the example.
When deploying TripleO upstream from stable/train, we need to override
the default ContainerCli to "podman" and not let "docker" since it's not
a thing anymore.
We kept it this way for backward compatibility in TripleO but in reality
when enabling HA on centos8 in Train, you need Podman.

Support TripleO deployment from stable/train

---

example-overrides/local-overrides-centos8-tripleo-train.yaml
playbooks/install_stack.yaml
playbooks/prepare_host.yaml
playbooks/prepare_stack.yaml
playbooks/templates/standalone_parameters.yaml.j2
playbooks/vars/defaults.yaml

For some reason, those PRs weren't in master anymore even if they were merged...
Re-adding them:
https://github.com/shiftstack/dev-install/pull/66
- Fix Ganesha binding when Manila is enabled
https://github.com/shiftstack/dev-install/pull/69
- Revert "Revert "Automate manila share type creation""
- manila: force OS_SHARE_API_VERSION to 2.60
- Disable snapshot-support for cephfsnfstype
https://github.com/shiftstack/dev-install/pull/79
- Allow to configure authorized SSH keys for stack user
https://github.com/shiftstack/dev-install/pull/80
- Use current-tripleo by default
https://github.com/shiftstack/dev-install/pull/81
- Fix ssh authorized keys
https://github.com/shiftstack/dev-install/pull/82
- Force podman for ContainerCli
- Update example overrides for upstream train

Re-add missing commits

---

README.md
playbooks/install_stack.yaml
playbooks/local_os_client.yaml
playbooks/roles/simpleca/tasks/main.yaml
playbooks/templates/standalone_parameters.yaml.j2
playbooks/vars/defaults.yaml

By setting `ssl_enabled` to true, dev-install will do the following:
* Generate a CA, re-using what Matt did when doing `make certs`.
* Generate a private key, a certificate and sign with the CA.
* The certificate is signed to allow DNS and IP addresses, for
control plane IP, public IP and the standalone_host, so the
certificate will be usable for different kind of endpoints
even though OpenStack TLS will be configured only with IP based
endpoints for Public interface only.
* When running `make local_os_client`, it will pull the CA from the host
on the local host so the client can use the OpenStack out of the box
using SSL.
This was manually tested with OSP 16.2.

Enable SSL support

---

Makefile
playbooks/validations.yaml

Add some variable validations, to prevent deployment issues later:
* standalone_host matches with ansible_host
* control_plane_ip is different from public_api
* standalone_role file actually exists

Add pre-deploy validations

---

playbooks/prepare_host.yaml
playbooks/templates/standalone_parameters.yaml.j2

* Split out creation task into multiple tasks
* Use direct io on loopback device
* Only ever create loopback device with systemd unit
* Use ansible modules for vg/lv creation
* Rename created volume group to vg_ceph

Make ceph vg creation idempotent

---

playbooks/files/cloud-to-env.py
playbooks/prepare_stack.yaml

Manila client as installed by RHEL/OSP doesn't have OSC support.
/cc @mandre

Use manila client instead of osc

---

playbooks/network.yaml
playbooks/roles/network_info/tasks/main.yaml

I can't install without this patch. deploy always fails with TripleO complaining that the network service failed.
Bonus: this patch auto-detects SR-IOV devices. We can use that to improve SR-IOV support.

Disable interfaces which aren't in use

---

README.md
playbooks/install_stack.yaml
playbooks/roles/simpleca/tasks/main.yaml
playbooks/vars/defaults.yaml

Allow a user to bring their own Certificate Authority to dev-install,
so when OpenStack will be deployed, the generated certificate will be
signed with this CA.
It's a famous customer use-case, and will also be used by our CI, so we
can rely on a stable CA and just generate ephemeral certificates when
deploying OpenStack.
Instead of generating all SSL files remotely, do it locally, it's more
secure.
The main reason of doing this is because we do not want the CA private
key to be on the remote host, this would be a security issue in case
someone has access to the host, they can compromise our CA

SSL: "Bring your own CA" support & generate SSL locally

---

playbooks/install_stack.yaml
playbooks/local_requirements.yaml
playbooks/prepare_host.yaml
playbooks/roles/rhsm/tasks/main.yaml
playbooks/templates/standalone_parameters.yaml.j2
playbooks/vars/defaults.yaml

When we want to deploy Red Hat OpenStack as customers would do, using
the product, we don't want to use the internal puddle (rhos-release).
For that we need to use Red Hat Subscription Manager (RHSM) which has
its Ansible role.
This patch will:
* deploy the role in ~/.ansible/roles
* provide safe defaults for OSP 16.1 (latest release)
* call the role when rhsm_enabled is set to True
* manage required modules
* generate CIP config using CLI
* login to the containe registry when deploying
More information about the role:
https://docs.openstack.org/project-deploy-guide/tripleo-docs/latest/features/rhsm.html

Support for RHSM

---

Makefile
playbooks/vars/defaults.yaml

When installing a cloud, it makes sense to run `local_os_client` by
default so the user can operate the OpenStack cloud immediately.
To improve the user experience, we enable SSL by default, with
self-signed CA & certificates, so the public endpoints are secure by
default.

UX improvements for security

---

playbooks/install_stack.yaml
playbooks/templates/dev-install_net_config.yaml.j2
playbooks/templates/standalone_parameters.yaml.j2
playbooks/vars/defaults.yaml

It is more secure to keep internal/admin networks under a secured
control plane network, and use the public interface for the public
endpoints.
* We will create external-network-vip.yaml environment, until the
upstream patch in THT will merge:
https://review.opendev.org/c/openstack/tripleo-heat-templates/+/793836
This environments helps to configure TripleO to use an external IP for
the public VIP.
* Configure standalone to run with local_ip, control plane IP and public
IP, and also load the network config that is done for Undercloud, this
is fine since TripleO Undercloud already separates public & internal
endpoints.
* Use 192.168.24.0/24 as default control plane network, keep first IP
for the local IP and second IP for the control plane VIP.

Separate control plane & public endpoints networks

---

playbooks/vars/defaults.yaml

This shouldn't be needed because we pull ceph-ansible from
rhceph-4-tools-for-rhel-8-x86_64-rpms and then everything else is
containerized.
I'm removing it because the repo isn't available in some RHSM
subscriptions for some reason. I'll propose a revert if I find out that
this patch caused more pain.

Remove rhceph-4-osd-for-rhel-8-x86_64-rpms from default OSP repos

---

playbooks/templates/dev-install_net_config.yaml.j2

- Switch bridge MTU to 1400 if tunnels are being used.
When using VXLAN tunnels between the bridges, it's important to set proper MTU because the
Ethernet frame is being encapsulated in `Ethernet + IP + UDP + Overlay Header`.
This means that the Maximum Transmission Unit for the underlay needs to be adjusted to something close to 1400.
Using 1400 is a safe number for now which should give up flexibility in
using IPv4 and IPv6 in the future.
- Remove default value for tunnel_remote_ips in template
The default value for tunnel_remote_ips is already sets in default vars,
we don't want to duplicate it in the template.

Bridging improvements

---

playbooks/install_stack.yaml
playbooks/vars/defaults.yaml

We need to manually add the CephNfs to the registry because it's
missing in the Standalone role for OSP16.1, there is a missing backport
from upstream to downstream:
https://review.opendev.org/c/openstack/tripleo-heat-templates/+/773205/
While this is being fixed via BZ#1969962, let's add the service
ourselves, which won't hurt any deployment (even master) since the list
will simply merge if the service already exists (which is the case on
> 16.1).

Workaround to make Manila working on OSP16.1

---

playbooks/templates/standalone_parameters.yaml.j2

Due to BZ#1901143 and BZ#1903005, we can't override the Ceph cluster
name where Manila is deployed.
In the case of our Edge setup, we only deploy Manila on the central
site so let's skip this parameter there and configure only the AZ
nodes.

Don't configure CephClusterName on central node

---

playbooks/prepare_stack.yaml

To make it easier to discover, let's rename the type that will be used
for Manila CSI testing, to be `default`
Technically it changes nothing but it'll make it so the Manila CSI
operator will create a storage class with the name
`csi-manila-default`; which is more generic than
`csi-manila-cephfsnfstype`.
More context: https://github.com/openshift/csi-driver-manila-operator/pull/103

Rename Manila share type

---

playbooks/prepare_stack.yaml

Create a security group that has a rule which authorizes SSH.
It can be used by anyone who need to allow SSH on their workloads, so
they don't have to do create it manually.
The name of the security group is `allow_ssh`.

prepare_stack: create allow_ssh security group

---

example-overrides/local-overrides-centos8-tripleo-master.yaml

If we want to deploy TripleO master, we need to use current-tripleo-dev
repo and not current-tripleo, let's just document it here in an example
that was tested and worked fine.

Add working example of overrides for tripleomaster deployment

---

playbooks/prepare_stack.yaml
playbooks/vars/defaults.yaml

Add a new option `swiftoperator_enabled` (true by default).
It helps to configure whether or not we want to add the swiftoperator role to
the openshift user in openshift project (in Keystone).
Set this to false and the openshift user won't have access
to Swift. It can be useful if you want to force OpenShift to
deploy the Image registry in Cinder instead of Swift.

Allow to disable swift for the openshift user

---

playbooks/prepare_stack.yaml

The snapshot support was added in recent version of OpenStack (current
master and backported to Wallaby).
For OSP16, we want to set it to False like it was the case before that
patch. But for new versions, we need to set it to True otherwise the
Manila Scheduler will fail to create shares:
http://paste.openstack.org/show/ivBPVOf9IcEOpUI9CfSL/

manila: create the share type with snapshot support when possible

---

playbooks/install_stack.yaml
playbooks/prepare_stack.yaml

* Switch ganesha_vip to use the public IP.
The reason is that VMs have no access to the control plane network (by
security reasons), so we would need a routable IP that the workloads
running in a VM can reach. For now let's use the public IP which
shouldn't be an issue. However we'll add IPtables rules to secure its
access from the OSP cloud only.
* Fix the snapshot support command, it was wrong and the syntax has been
fixed.

Manila changes

---

playbooks/install_stack.yaml

If we deploy OSP with Kernel args, we need to reboot. It's possible to
configure Kernel args without SR-IOV, so let's add a condition, that
will reboot if we use dpdk_kernel_args param.

Add a condition to reboot the node after deployment

---

playbooks/install_stack.yaml
playbooks/vars/defaults.yaml

If we set the `dpdk_kernel_args` parameter but don't want SR-IOV to be
configured, we can now do it with that patch, since we separate the
list of services for DPDK & SR-IOV.

Allow to deploy OSP with CPU partitioning without SR-IOV

---

playbooks/prepare_host.yaml

use the `needs-restarting` tool to figure out if a server actually
needs a reboot. In some cases, it doesn't (ie the kernel is already up
to date, etc), so we'll save deployment time.

prepare_host: only reboot if actually needed

---

README.md
playbooks/install_stack.yaml
playbooks/templates/standalone_parameters.yaml.j2
playbooks/vars/defaults.yaml

They are too rigid, let's just keep the kernel_args for now.
Users can still use extra_heat_params for their DPDK configs.

Remove DPDK variables

---

playbooks/prepare_host.yaml

The task will be marked as failed when the reboot is needed, this patch
fixes that by ignoring the error. It is fine, because a non-zero return
code means a reboot is needed.

prepare_host: fix needs-reboot task

---

playbooks/install_stack.yaml
playbooks/vars/defaults.yaml

Enables the env file /usr/share/openstack-tripleo-heat-templates/environments/low-memory-usage.yaml,
this reduces the RAM usage from 16GB to 6GB.

install_stack: Add low memory option

---

playbooks/install_stack.yaml
playbooks/prepare_host.yaml

We do not need to reboot after upgrading the rpms if we deploy TripleO
with SR-IOV or/and Kernel args, because we reboot anyway right after
TripleO being deployed. We'll save one reboot.

Save one reboot when using SR-IOV or Kernel args

---

playbooks/install_stack.yaml
playbooks/templates/standalone_parameters.yaml.j2

Ceph has given up ceph-ansible and therefore TripleO had to remove its
support going forward.
This patch will detect if ceph-ansible can still be used and if not
it'll configure ceph using `cephadm`.
From a user standpoint, dev-install still offers 3 options:
* Disable the management of Ceph from dev-install; if users don't want
Ceph or if they want to use `extra_heat_params`.
* Let cephadm to install Ceph OSDs on available disks that aren't
rotational (for performance purposes). This is different from
ceph-ansible where we could choose the disks, but one can achieve it
via option 1 if they don't have SSD/NVME disks.
* Let dev-install creating LVM resources on a loop device and let
cephadm to use these volumes to configure Ceph. Note that cephadm
doesn't need the DB volume but this …

Add support for cephadm instead of ceph-ansible

---

playbooks/templates/standalone_parameters.yaml.j2

When deploying a `central` node, let's enable
NovaSchedulerDiscoverHostsInCellsInterval parameter in TripleO; which
will check if a new compute is deployed every 2 minutes.
When detected, it will add the new compute to the cell and the compute
will be able to be schedulable for new VMs.
Note: this feature is by default disabled in TripleO because there is
a race condition with Ironic, but since we don't deploy/use baremetal
API here, we can safely enable it.

DCN: enable dynamic compute discovery

---

playbooks/templates/dev-install_net_config.yaml.j2

The bridge takes the highest MTU of the interfaces connected to it.
So it was always set to 1500 even if we force it to 1400, because dummy
nics were using 1500.
Now that we set it to 1400, the bridge will be 1400 too, and it helps
when setting up VXLAN tunnels in multinode environment.
This has been tested against a real environment.

Configure MTU on dummy interface, not the bridge

---

playbooks/prepare_host.yaml

It's possible that CentOS or RHEL images come with persistent NIC
naming disabled and we don't want that because it'll cause random
networking issues after reboots.
Let's make sure we remove that argument from the grub cmd and rebuild
grub.

prepare_host: add task to make sure persistent NIC is enabled

---

example-overrides/local-overrides-osp16-2.yaml
playbooks/prepare_host.yaml
playbooks/vars/defaults.yaml

* Add an example of 16.2-beta config.
* Introduce `virt_release` to override the default virt:rhel module that is installed. Note that the virt module needs to be set to `av` on RHEL 8.4 and onward.
16.2 is not GA'ed yet so it's safer to use 16.1 when downloading content from puddles. Content from 16.2 might be unstable.

Safe defaults to install OSP 16.1 and 16.2

---

playbooks/install_stack.yaml
playbooks/prepare_stack.yaml
playbooks/templates/standalone_parameters.ceph_ansible.yaml.j2

A few months ago we decided that Manila shares would listen on public
network, because we don't have a storage network in Standalone.
For that to happen, we need to configure Ganesha to listen on the
public network (and not the control plane), so we need to configuring
the following:
* ganesha_vip: for pacemaker to create the VIP
* ceph_nfs_bind_addr: for ceph-ansible, taking care of configuring
ganesha with the public IP
* tripleo_cephadm_ceph_nfs_bind_addr: for cephadm, taking care via
tripleo-ansible of configuring ganesha with the public IP.
50 shares doesn't seem enough when running the CSI test suite in parallel mode.
Let's increase it to 150 shares and 150 snapshots

Combined improvements for Manila

---

example-overrides/local-overrides-osp16-2-with-pcipassthrough.yaml

All the necessary parameters to configured pci passthrough can be specified in the local_override.yaml file

PCI passthrough local_override.yaml example

---

playbooks/templates/dev-install_net_config.yaml.j2
playbooks/templates/standalone_parameters.yaml.j2

When doing multinode, we connect the br-ctlplane bridges with VXLAN
tunnels, so the bridge has an MTU of 1400 (since the interface has
1500 in most infras).
However when creating Neutron tenant networks that will use overlay, on
top of these bridges, we need to lower the default MTU (1500) to work
in this setup, so using 1300 should be safe, since the tunnels are
1400.

Lower the Neutron global MTU in multinode

---

playbooks/templates/dev-install_net_config.yaml.j2

in the jinja template the logical test should include "is defined"
for checking a variable has been defined.
otherwise playbook fails with 
TASK [Create dev-install_net_config.yaml] ****************************************************************************
fatal: [standalone]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dcn_az' is undefined"}

fix mtu settings for ovs-bridge

---

playbooks/templates/standalone_parameters.yaml.j2

By default, volume states can only be changed by admin but in
dev-install cases, we are operating our cloud and sometimes need to
reset the state of a volume.
e.g. in OpenShift CI, sometimes volumes aren't cleaned correctly and we
have to manually clear them up. Thanks to this patch, the tenant will
be able to set the state of their own volumes.

Configure Cinder API to allow users to set volume states

---

playbooks/roles/simpleca/tasks/main.yaml

We shouldn't assume the script is run on something having yum/dnf. Let's
ignore the error of the task requiring it and assume that user can
install it manually if it's not there.
Also it prevents from errors like below when user running the playbook
isn't added to `wheel` group. You can fix it with `sudo gpasswd -a
<user> wheel` BTW.
fatal: [standalone]: FAILED! => {"changed": false, "msg": ["Could not
detect which major revision of yum is in use, which is required to
determine module backend.", "You can manually specify
use_backend to tell the module whether to use the yum (yum3) or dnf
(yum4) backend})"]}

Ignore error if yum/dnf fails on localhost

---

playbooks/install_stack.yaml

We don't need to deploy them all, it can actually causes some packaging
dependencies problems on OSP 16.1.

Only deploy useful tuned profiles

---

playbooks/templates/standalone_parameters.yaml.j2

KernelArgsDeferReboot was added in recent releases to defer the reboot
after kernel args sets.
We handle the reboot ourselves in dev-install, since it's a standalone
install.
Before we were relying on Ansible group vars, but now we have
KernelArgsDeferReboot that sets Host vars for
tripleo_kernel_defer_reboot.

Set KernelArgsDeferReboot to true

---

playbooks/install_stack.yaml
playbooks/templates/standalone_parameters.yaml.j2

Fix some extra config for Manila ganesha IP
Tuned RT isn't available from OSP 16.2 and not really needed in
standalone use case.
Installing CPU partitioning should be enough.

Few fixes for OSP 16.2

---

playbooks/templates/standalone_parameters.yaml.j2

In a previous commit, we forgot to add a new condition to configure
StandaloneExtraConfig when Manila is enabled.
This patch will fix it.

Fix StandaloneExtraConfig

---

playbooks/install_stack.yaml
playbooks/vars/defaults.yaml

Add a new parameter, called `ovn_enabled` set to True by default.
When set to False, OVS will be deployed instead of OVN when deploying
SR-IOV.

SR-IOV: add support for OVS

---

playbooks/install_stack.yaml
playbooks/vars/defaults.yaml

Add a task to unregister RHSM from the system unless `rhsm_ephemeral`
is set to False.
Note that this is set to True by default because most of subscriptions
have limited numbers of systems.
In production or CI environments, you want to set it to False, so the
system can get upgrades on day 2.

Add a task to unregister RHSM

---

playbooks/roles/network_info/tasks/main.yaml

Reverts shiftstack/dev-install#166
This is a broken change, we'll address that later again.

Revert "Fix failure if netaddr isn't available on controller"

---

playbooks/install_stack.yaml
playbooks/network.yaml
playbooks/prepare_stack.yaml
playbooks/templates/dev-install_net_config_dpdk.yaml.j2
playbooks/vars/defaults.yaml

Re-use `hostonly` provider network when DPDK is enabled and instead of
adding a dummy interface (dummy1), just use the physical interface that
we want to use for DPDK.
This will avoid confusions when our users see multiple provider
networks.
In fact, one is enough and should be used.
Note: we maintain the SRIOV provider network separated, since it's using
another kind of interface etc.

Simplify DPDK integration with provider network

---

playbooks/prepare_stack.yaml

This complements the 'allow_ssh' security group rule we already create.

Create 'allow_ping' security group

---

playbooks/prepare_host.yaml

If you don't do this, Ceph will moan about the presence of a bootloader. Use of `wipefs` is an alternative to using ceph-volume's `zap` command, which requires ceph be already installed on the host.

Wipe disk(s) used for ceph

---

playbooks/local_os_client.yaml
playbooks/vars/defaults.yaml

"--user" shouldn't be specified when installing
pip packages install a python virtualenv. Setting it causes
the following error:
TASK [Install openstack client locally] ****************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (pip) module: when. Supported parameters include: virtualenv_site_packages, editable, executable, virtualenv, name, extra_args, virtualenv_command, virtualenv_python, state, umask, chdir, requirements, version."}

Fix osc install when running in a virtualenv

---

playbooks/install_stack.yaml

Tripleoclient removed --standalone option some time ago:
https://review.opendev.org/c/openstack/python-tripleoclient/+/753447
And the TripleO Operator Ansible was updated to not use it anymore:
https://review.opendev.org/c/openstack/tripleo-operator-ansible/+/753853
In dev-install, we now figure out if the version of TripleO that is
being installed on CentOS needs or doesn't need that flag.
Note that we'll have to figure out how to make it work for OSP 17.1 and
OSP 18, since they'll probably contain these changes, but we have time
for now.

install_stack: disable the use of --standalone arg in recent TripleO

---

playbooks/prepare_host.yaml

We shouldn't be checking for a string. Just make sure it's not a boolean (used for OSP 17 or later)

'ceph_devices' is a list, not a string

---

README.md
example-overrides/local-overrides-centos9-tripleo-master.yaml
playbooks/network.yaml
playbooks/prepare_host.yaml
playbooks/vars/defaults.yaml

* Update README
* Add example overrides for centos9 deployed on tripleo master
* Install modules only for 8 stream. No modules are required on 9

CentOS 9 support

---

playbooks/prepare_host.yaml

This hides an ugly (if innocuous) warning.

Mark non-zero 'needs-restarting' retcode as "expected"

---

example-overrides/local-overrides-basic.yaml

While you can in theory use dev-install with the default local-overrides generated by 'make config', most people will want an external network and (most likely) a unique name for their cloud in 'clouds.yaml'. The existing local-overrides files focus on scenarios described in the "Advanced Features" section of the README but there is no example for sane, non-advanced configuration. Add one now, avoiding the need for me to relearn this this stuff each time I use dev-install

Add a minimal local-overrides sample

---

README.md
playbooks/prepare_stack_testconfig.yaml

Two changes:
- README: Document 'prepare_stack_testconfig' playbook
- Use correct ansible.builtin.copy return value

Document/fix 'prepare_stack_testconfig' playbook

---

playbooks/templates/dev-install_net_config.yaml.j2
playbooks/templates/dev-install_net_config_dpdk.yaml.j2

the primary nic should not be overriden because we have some mechanism
to find out which interface is used for public network.
let's just override all the rest but not the primary nic to avoid
complexity.

net_config: don't override primary nic

---

playbooks/prepare_stack.yaml
playbooks/templates/dev-install_net_config.yaml.j2
playbooks/templates/dev-install_net_config_dpdk.yaml.j2
playbooks/templates/standalone_parameters.yaml.j2
playbooks/vars/defaults.yaml

From now, the `hostonly` network will be configured in dual stack so we
can easily play with IPv6 on that provider network.
We'll use 2001:db8::/64 cidr and make sure that we can create VMs on
that network, and ping from each other and even reach outside out of the
box.
Tested on OSP 16.2.

IPv6 Dual Stack on hostonly network

---

playbooks/install_stack.yaml
playbooks/prepare_host.yaml
playbooks/templates/standalone_parameters.yaml.j2

To support RHEL9/OSP17, we need to stop hardcoding RHEL8.
In this patch we can re-use an ansible fact to figure out which number
is actually deployed.
Also fixing ceph on OSP17.

RHEL9 - OSP17 required changes

---

playbooks/templates/dev-install_net_config.yaml.j2
playbooks/templates/dev-install_net_config_dpdk.yaml.j2
playbooks/vars/defaults.yaml

* br-ex/public MTU default remains 1500, but is now overridable
* br-ctlplane/br-hostonly can be overridable and default is 1400
* Neutron MTU for tenant network remains 1300 by default but this needs
to be bumped if double encapsulation is done with IPv6, see
https://issues.redhat.com/browse/OCPBUGS-2921

Allow to override MTUs

---

playbooks/vars/defaults.yaml

This commit converts the mtu to int before concataneting, otherwise we would get the following error:
"Unexpected templating type error occurred on ({{ ctlplane_mtu + 100 }}): can only concatenate str (not \"int\") to str"}"

Fix MTU concatenation

---

playbooks/vars/defaults.yaml

Due to a known issue with OVN-Kubernetes the default Neutron MTU should be at least 1400.

Increase default Neutron MTU

---

playbooks/prepare_host.yaml

We now have 2022 certs that we need to support alongside with the old
CA.

prepare_host: add new RH CA certs

---

playbooks/install_stack.yaml
playbooks/prepare_host.yaml
playbooks/templates/standalone_parameters.yaml.j2
playbooks/vars/defaults.yaml

Allow to easily install Barbican with the simple crypto plugin.
This is opinionated but can easily be overridden.
NOTE: this PR also fixes a few lint errors.

Allow to easily enable Barbican (with Simple Crypto)

---

playbooks/templates/dev-install_net_config.yaml.j2
playbooks/vars/defaults.yaml

Sometimes, the default route can't be applied on br-ex via DHCP for some
reasons, and it can be useful to add this route manually before
os-net-config is creating the br-ex bridge. It'll avoid networking
issues.
This feature is disabled by default for backward compability.

Add `public_default_route` to allow applying default route

---

playbooks/templates/standalone_parameters.yaml.j2

We have observed in our CI that sometimes volumes aren't detached when
being removed.
This can be due to the density of testing in our environment.
To address this, we allow tenants to force-detach their own volumes.
In our CI scripts, we'll use that to force detach volumes before they
are cleaned-up in the periodic cleanup jobs.

CinderApiPolicies: allow force-detach

---

.ansible-lint

These errors are not important to us.

Skip `var-naming[no-role-prefix]` ansible-lint test

---

playbooks/prepare_host.yaml

Sometimes the `net.ifnames=0` is the last item in the default grub
arguments so the grep that was setup initially wouldn't match.
Let's just match `net.ifnames=0` and remove it.

prepare_host: fix inconsistent nic naming on RHEL 9

---

playbooks/prepare_stack.yaml

Allow the users to use some ephemeral storage when they need.
Note that that storage will have to be explicitely requested when
creating a server, the value in the flavor is just a quota which can be
used at server creation.

flavors: add ephemeral storage

---

playbooks/roles/operators/tasks/main.yaml

The repo was retired, so we need to checkout the latest commit before it
gets empty.

Checkout tripleo operators from latest commit

---

README.md

Add troubleshooting section and rework README

---

playbooks/roles/simpleca/tasks/main.yaml

In certain cases, we want to proxify endpoints through the hostonly
interfaces (ipv4 and ipv6) so let's relax the certificate and allow the
endpoints to be on these IPs too.

ssl: allow cert to be used by hostonly IPs
